development:
  db:
    open: dbname=babou host=localhost sslmode=disable
  site:
    domain: localhost
    port: 8080
  # This section will be used to generate announce URLs
  # It should represent your tracker's PUBLIC domain/port
  # 
  # If you'd like to run your tracker(s) on a different port, 
  # please pass a command-line flag.
  tracker:
    domain: localhost
    port: 4200
  # Configures the babou event bridge
  # Use `lo` if you will be running a single instance.
  events:
    transport: lo # Must be one of: unix, tcp, lo
    peers:
      - transport: unix
        socket: /tmp/babou.8081.sock
      - transport: tcp
        address: 127.0.0.1
        port: 3000
